language: ruby
rvm:
- 2.6.3
before_install:
- gem install bundler
before_script:
- cp config/database.yml.ci config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
— bundle install — jobs=3 — retry=3
— bundle exec rake db:create
— bundle exec rake db:migrate
— bundle exec rspec
